# Nom de l'application
spring.application.name=ApiGateway-4SA11

# Port du serveur API Gateway
server.port=8093

# Configuration Eureka pour l'enregistrement du service API Gateway
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Type d'application : Spring WebFlux (reactive)
spring.main.web-application-type=reactive

# Logs pour le débogage de Gateway et Reactor Netty
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# Désactivation de la sécurité Spring (si non utilisée dans l'API Gateway)
spring.security.enabled=false

# Activation de la découverte de services via Eureka
spring.cloud.gateway.discovery.locator.enabled=true

# Permettre le remplacement des beans dans Spring
spring.main.allow-bean-definition-overriding=true

# Configuration globale CORS (Accès depuis le frontend Angular)
spring.cloud.gateway.globalcors.allowed-origins=http://localhost:4200
spring.cloud.gateway.globalcors.allowed-methods=GET, POST, PUT, DELETE
spring.cloud.gateway.globalcors.allowed-headers=*

# Route pour USERS service via Eureka (Assurez-vous que le service USERS est bien enregistré dans Eureka)
spring.cloud.gateway.routes[0].id=USERS
spring.cloud.gateway.routes[0].uri=lb://USERS
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Route pour VULNERABILITIES service via Eureka (Assurez-vous que le service VULNERABILITIES est bien enregistré dans Eureka)
spring.cloud.gateway.routes[1].id=VULNERABILITIES
spring.cloud.gateway.routes[1].uri=lb://VULNERABILITIES
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/vulnerabilities/**

# Route pour EXPLOIT_REPORTS service via Eureka (Assurez-vous que le service EXPLOIT_REPORTS est bien enregistré dans Eureka)
spring.cloud.gateway.routes[2].id=EXPLOIT_REPORTS
spring.cloud.gateway.routes[2].uri=lb://EXPLOIT_REPORTS
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/exploit-reports/**
